import type { BlockDefinition } from '@/types/builder';
import ColumnsIcon from 'lucide-vue-next/dist/esm/icons/columns-2.js';
import { defineAsyncComponent } from 'vue';

export default {
    name: 'columns',
    label: 'Columns',
    icon: ColumnsIcon,
    description: 'Create multi-column layouts.',
    component: defineAsyncComponent(() => import('@/shared/blocks/ColumnsBlock.vue')),
    settings: [
        {
            key: 'layout',
            type: 'toggle_group',
            label: 'Layout',
            options: [
                { label: '50/50', value: '1-1' },
                { label: '1/3 - 2/3', value: '1-2' },
                { label: '2/3 - 1/3', value: '2-1' },
                { label: '3 Cols', value: '1-1-1' },
                { label: 'Full', value: '1' }
            ],
            default: '1-1',
            tab: 'style'
        },
        {
            key: 'stackOn',
            type: 'select',
            label: 'Stack Columns On',
            options: [
                { label: 'Mobile Only', value: 'sm' },
                { label: 'Mobile & Tablet', value: 'md' },
                { label: 'All Screens', value: 'lg' },
                { label: 'Never', value: 'never' }
            ],
            default: 'never',
            tab: 'style'
        },
        {
            key: 'direction',
            type: 'toggle_group',
            label: 'Direction (Desktop)',
            options: [
                { label: '→', value: 'row' },
                { label: '←', value: 'row-reverse' },
                { label: '↓', value: 'column' },
                { label: '↑', value: 'column-reverse' }
            ],
            default: 'row',
            tab: 'style'
        },
        {
            key: 'mobileDirection',
            type: 'toggle_group',
            label: 'Direction (Mobile)',
            options: [
                { label: '→', value: 'row' },
                { label: '←', value: 'row-reverse' },
                { label: '↓', value: 'column' },
                { label: '↑', value: 'column-reverse' }
            ],
            default: 'column',
            condition: (settings: Record<string, unknown>) => settings.stackOn !== 'never',
            tab: 'style'
        },
        {
            key: 'width',
            type: 'select',
            label: 'Container Width',
            options: [
                { label: 'Standard', value: 'max-w-7xl' },
                { label: 'Full', value: 'max-w-full' }
            ],
            default: 'max-w-7xl',
            tab: 'style'
        },
        {
            key: 'padding',
            type: 'toggle_group',
            label: 'Padding',
            options: [
                { label: 'None', value: 'py-0' },
                { label: 'Md', value: 'py-16' },
                { label: 'Lg', value: 'py-24' }
            ],
            default: 'py-16',
            tab: 'style'
        },
        {
            key: 'bgColor',
            type: 'color',
            label: 'Background Color',
            default: 'transparent',
            tab: 'style'
        }
    ],
    defaultSettings: {
        layout: '1-1',
        // Legacy (for backward compatibility)
        columns: [],
        // Modern: Array of Column block objects
        blocks: [
            {
                id: 'default-col-1', // Will be regenerated by builder
                type: 'column',
                settings: { blocks: [] }
            },
            {
                id: 'default-col-2',
                type: 'column',
                settings: { blocks: [] }
            }
        ],
        customWidths: [50, 50],
        stackOn: 'never',
        direction: 'row',
        mobileDirection: 'column',
        padding: 'py-16',
        width: 'max-w-7xl',
        bgColor: 'transparent',
        radius: 'rounded-none',
        animation: '',
        visibility: { mobile: true, tablet: true, desktop: true }
    }
} as BlockDefinition;
