import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import Badge from "@/shared/components/ui/Badge.vue";

describe('Badge.vue', () => {
    it('renders correctly with default slot', () => {
        const wrapper = mount(Badge, {
            slots: {
                default: 'Active'
            }
        })
        expect(wrapper.text()).toBe('Active')
    })

    it('applies correct classes for different variants', () => {
        const variants = ['default', 'secondary', 'destructive', 'outline']

        variants.forEach(variant => {
            const wrapper = mount(Badge, {
                props: { variant: variant as any }
            })
            // We don't check exact classes because they are generated by CVA, 
            // but we ensure the component mounts and has some classes.
            expect(wrapper.classes()).toContain('inline-flex')
        })
    })
})
