#!/usr/bin/env bash
# Unified OpenAPI export for ja-core_engine.
# 1) Scramble → docs/api/console.openapi.json (Laravel route API)
# 2) dynamic:openapi → docs/api/dynamic-*.openapi.json (Data Model Studio)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND="${ROOT}/backend"
OUT="${ROOT}/docs/api"
mkdir -p "$OUT"

echo "==> Scramble export (console /api routes)"
(
  cd "$BACKEND"
  php artisan scramble:export --path="${OUT}/console.openapi.json"
)

echo "==> Dynamic Data Model OpenAPI"
(
  cd "$BACKEND"
  php artisan dynamic:openapi --output="${OUT}"
)

# Index file for agents
cat >"${OUT}/INDEX.md" <<EOF
# OpenAPI export index

Generated by \`bash scripts/export-openapi.sh\` / \`npm run docs:openapi\`.

| Artifact | Source |
| :--- | :--- |
| \`console.openapi.json\` | Dedoc Scramble (\`php artisan scramble:export\`) |
| \`dynamic-*.openapi.json\` | Data Model Studio (\`php artisan dynamic:openapi\`) |

Do not hand-edit JSON. Regenerate after API or model field changes.

Docs: [reference/http-api.md](../reference/http-api.md)
EOF

echo "OK  OpenAPI artifacts in ${OUT}"
ls -la "$OUT"
